// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 10:11:03 SAST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "clay.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

