// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 10:11:03 SAST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package clay

/*
#cgo CFLAGS: -I../C
#include "clay.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// HEADER as defined in go-clay/<predefined>:402
	HEADER = 1
)

const ()
