// MIT

// WARNING: This file has automatically been generated on Mon, 10 Nov 2025 10:11:03 SAST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package clay provides Go bindings for the Clay UI layout library. Clay is a high-performance, render engine agnostic UI layout library.
*/
package clay
